version: "3.7"

services:
  scanner_tsr:
    image: macterra/metatron-scanner
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment:
      - SCANNER_CHAIN=TSR
      - SCANNER_START=100999
    env_file:
      - metatron.env
      
  scanner_tbtc:
    image: macterra/metatron-scanner
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment:
      - SCANNER_CHAIN=tBTC
      - SCANNER_START=2034420
    env_file:
      - metatron.env
      
  scanner_btc:
    image: macterra/metatron-scanner
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment: 
      - SCANNER_CHAIN=BTC
      - SCANNER_START=691459
    env_file:
      - metatron.env

  vault:
    image: macterra/metatron-vault
    ports:
      - "5000:5000"
    depends_on: 
      - ipfs
    env_file:
      - metatron.env

  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    ports:
      - "4001"
      - "8080:8080"
      - "5001"
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs

  redis:
    image: redis:6.2.4
    ports:
      - "6397"
    volumes:
      - ./data/redis:/data
