version: "3.7"

services:
  tesseract:
    image: macterra/tesseract-node:v0.06.08
    volumes:
      - /mnt/volume_tor1_02/tesseract:/data
    ports:
      - 17331:17331
      - 18331:18331

  testbtc:
    image: macterra/bitcoin-node:v0.18.0
    volumes:
      - /mnt/volume_tor1_02/bitcoin:/data
    ports:
      - 18332:18332
      - 18333:18333

  bitcoin:
    image: macterra/bitcoin-node:v0.18.0
    volumes:
      - /mnt/volume_tor1_03/bitcoin:/data
    ports:
      - 8332:8332
      - 8333:8333

  scanner_tsr:
    image: macterra/metatron-scanner:v21.06.13
    volumes:
      - ./data:/app/data
    depends_on: 
      - redis
      - ipfs
      - tesseract
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=TSR
      - SCANNER_START=95000
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.tsr.env
      
  scanner_tbtc:
    image: macterra/metatron-scanner:v21.06.13
    volumes:
      - ./data:/app/data
    depends_on: 
      - redis
      - ipfs
      - testbtc
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=tBTC
      #- SCANNER_START=1972048
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.tbtc.env
      
  scanner_btc:
    image: macterra/metatron-scanner:v21.06.13
    volumes:
      - ./data:/app/data
    depends_on: 
      - redis
      - ipfs
      - bitcoin
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=BTC
      #- SCANNER_START=679432
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.btc.env

  webui:
    image: macterra/metatron-webui:v21.05.16
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment:
      - DB_HOST=redis
      - IPFS_HOST=ipfs

  vault:
    image: macterra/metatron-vault:v21.06.14
    ports:
      - "5000:5000"
    environment: 
      - DB_HOST=redis
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.tsr.env

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs

  redis:
    image: redis:latest
    ports:
      - "6397"
    volumes:
      - ./data/redis:/data
  
