version: "3.7"

services:
  scanner:
    image: macterra/metatron:latest
    #command: tail -F /dev/null
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs

  webui:
    image: macterra/metatron-webui:latest
    #command: tail -F /dev/null
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001"
      - "8080"
      - "5001"
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs

  