version: "3.7"

services:
  scanner_tsr:
    image: macterra/metatron
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=TSR
      - SCANNER_START=91796
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.tsr.env
      
  scanner_tbtc:
    image: macterra/metatron
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=tBTC
      - SCANNER_START=1972048
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.tbtc.env
      
  scanner_btc:
    image: macterra/metatron
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=BTC
      #- SCANNER_START=679432
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.btc.env

  webui:
    image: macterra/metatron-webui
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
    environment: 
      - DB_HOST=redis
      - IPFS_HOST=ipfs

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001"
      - "8080"
      - "5001"
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs

  redis:
    image: redis:latest
    ports:
      - "6397"
    volumes:
      - ./data/redis:/data
