version: "3.7"

services:
  scanner_tsr:
    image: macterra/metatron-scanner
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=TSR
      - SCANNER_START=100999
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.tsr.env
      
  scanner_tbtc:
    image: macterra/metatron-scanner
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=tBTC
      #- SCANNER_START=1972048
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.tbtc.env
      
  scanner_btc:
    image: macterra/metatron-scanner
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - redis
    environment: 
      - SCANNER_DBHOST=redis
      - SCANNER_CHAIN=BTC
      #- SCANNER_START=679432
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.btc.env

  vault:
    image: macterra/metatron-vault
    ports:
      - "5000:5000"
    environment: 
      - DB_HOST=redis
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    depends_on: 
      - ipfs
    env_file:
      - credentials.vault.env

  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    ports:
      - "4001"
      - "8080"
      - "5001"
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs

  redis:
    image: redis:6.2.4
    ports:
      - "6397"
    volumes:
      - ./data/redis:/data
