version: "3.7"

services:
  tesseract:
    image: macterra/tesseract-node:v0.06.08
    volumes:
      - ./data/tesseract:/data
    ports:
      - "17331"
      - "18331"

  scanner_tsr:
    image: macterra/metatron:latest
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs
      - tesseract
    environment: 
      - SCANNER_CHAIN=TSR
      - SCANNER_START=91796
      - IPFS_CONNECT=/dns/ipfs/tcp/5001/http
    env_file:
      - credentials.tsr.env
      
  webui:
    image: macterra/metatron-webui:latest
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on: 
      - ipfs

  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "4001"
      - "8080"
      - "5001"
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs
