version: "3.7"

services:
  tesseract:
    image: macterra/tesseract-node:v21.08.03
    volumes:
      - ./tesseract:/data
    ports:
      - 7337:7337
      - 8337:8337

  scanner_tess:
    image: macterra/metatron-scanner:v21.07.24
    volumes:
      - ./data:/app/data
    depends_on: 
      - redis
      - ipfs
      - tesseract
    environment: 
      - SCANNER_CHAIN=TESS
      - SCANNER_START=1
    env_file:
      - metatron.env
      
  vault:
    image: macterra/metatron-vault:v21.08.15
    ports:
      - "5000:5000"
    env_file:
      - metatron.env

  ipfs:
    image: ipfs/go-ipfs:v0.8.0
    ports:
      - "4001:4001"
      - "8080:8080"
      - "5001:5001"
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs

  redis:
    image: redis:6.2.4
    ports:
      - "6397"
    volumes:
      - ./data/redis:/data
  
